[package]
name = "octopusxt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = { version = "0.15.0", git = "https://github.com/paritytech/subxt.git", rev = "a701d80e24fdc" }
async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate/", branch = "master" }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }
env_logger = "0.8.3"
hex = "0.4.3"