[package]
name = "octopusxt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = { version = "0.15.0", git = "https://github.com/octopus-network/substrate-subxt.git", branch = 'feature/beefy' }
# subxt = { version = "0.15.0", path = "../substrate-subxt" }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "time", "sync"] }
sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }
env_logger = "0.8.3"
log = { version = "0.4.0", default-features = false }
hex = "0.4.3"
jsonrpsee = { version = "0.5.1", features = ["macros", "ws-client", "http-client"] }
prost-types = { package = "informalsystems-prost-types", version = "0.8.1", default-features = false }
tendermint-proto = { version ="0.22.0", default-features = false }
ibc = { git  = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/beefy" }
# ibc = { version= "0.7.3", path = "../ibc-rs/modules" }
ibc-proto = { git  = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/beefy" }
# ibc-proto = { version= "0.11.0", path = "../ibc-rs/proto" }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
beefy-primitives = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
beefy-light-client = { git = "https://github.com/octopus-network/beefy-light-client.git", default-features = false }
#beefy-light-client = { path = "../beefy-light-client", default-features = false }
beefy-merkle-tree = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", features = ["keccak"], default-features = false }

[dev-dependencies]
hex-literal = "0.3"

[patch.crates-io]
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
ics23                   = { git = "https://github.com/informalsystems/ics23.git", rev = "4461b673" }
safe-regex          = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-regex-macro    = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-regex-compiler = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-quote          = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-proc-macro2    = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
tonic = { package = "informalsystems-tonic", git = "https://github.com/informalsystems/tonic.git", rev = "99edfe23" }
#tendermint= { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#ics23                   = { git = "https://github.com/informalsystems/ics23.git", branch = "master" }
#safe-regex          = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
#safe-regex-macro    = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
#safe-regex-compiler = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
#safe-quote          = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
#safe-proc-macro2    = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
