[package]
name = "octopusxt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = { version = "0.15.0", git = "https://github.com/octopus-network/substrate-subxt.git", branch = 'octopus-v0.9.12' }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "time", "sync"] }
sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }
env_logger = "0.8.3"
tracing = { version = "0.1.28", default-features = false }
hex = "0.4.3"
jsonrpsee = { version = "0.5.1", features = ["macros", "ws-client", "http-client"] }
prost-types = { version = "0.9.0", default-features = false }
serde = { version = "1.0.130", default-features = false }
libsecp256k1 = { version = "0.7.0", features = ["static-context"], default-features = false }
tendermint-proto = { version ="0.23.5", default-features = false }
ibc = { git  = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/merge-upstream-ibc-rs" }
ibc-proto = { git  = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/merge-upstream-ibc-rs" }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
beefy-primitives = { git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
beefy-merkle-tree = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", features = ["keccak"], default-features = false }
beefy-light-client = { git = "https://github.com/octopus-network/beefy-light-client.git", default-features = false }


[dev-dependencies]
hex-literal = "0.3"
chrono = "0.4"

[patch.crates-io]
tendermint                        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-proto                  = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-light-client-verifier  = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
