[workspace]
members = [
    "module",
    "octopusxt-cli",
]


[patch.crates-io]
# this is for subxt
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
# fix 1.0.98 group is private
syn =  { git = "https://github.com/DaviRain-Su/syn.git", branch = "branch-1.0.97" }

tendermint = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "feature/add-hostfunction" }
tendermint-proto = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "feature/add-hostfunction" }
tendermint-light-client-verifier = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "feature/add-hostfunction" }
tendermint-testgen = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "feature/add-hostfunction" }
tendermint-rpc = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "feature/add-hostfunction" }
tendermint-light-client = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "feature/add-hostfunction" }

ics23 = { git = "https://github.com/confio/ics23.git", branch = "master" }